apiVersion: v1
entries:
  gomydesk:
  - apiVersion: v2
    appVersion: v0.1.2
    created: "2022-12-23T11:50:23.476211-08:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 853fee1e89fccc357d6354a50de5765ab0b903118e864b96d4718318ccc1b930
    name: gomydesk
    type: application
    urls:
    - gomydesk-v0.1.2.tgz
    version: v0.1.2
  - apiVersion: v2
    appVersion: v0.1.1
    created: "2022-12-23T11:50:23.474859-08:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 369dc17a69f6155845120e368584af0633ce12eb683a0edd454c81d2adbd9ec5
    name: gomydesk
    type: application
    urls:
    - gomydesk-v0.1.1.tgz
    version: v0.1.1
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2022-12-23T11:50:23.473244-08:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: d8ccda0d893ab80689f55623c2188d550fc62f8eb78a5a4edcc19131c5d12feb
    name: gomydesk
    type: application
    urls:
    - gomydesk-v0.1.0.tgz
    version: v0.1.0
generated: "2022-12-23T11:50:23.471582-08:00"
