apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gomydesk.fullname" . }}-manager-rolebinding
  labels:
    {{- include "gomydesk.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gomydesk.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "gomydesk.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gomydesk.fullname" . }}-proxy-rolebinding
  labels:
    {{- include "gomydesk.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gomydesk.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "gomydesk.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
