apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gomydesk.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "gomydesk.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gomydesk.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "gomydesk.serviceAccountName" . }}
