apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "gomydesk.labels" . | nindent 4 }}
  name: {{ include "gomydesk.fullname" . }}-manager-metrics-service
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    {{- include "gomydesk.labels" . | nindent 4 }}
