{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gomydesk.serviceAccountName" . }}
  labels:
{{ include "gomydesk.labels" . | nindent 4 }}
{{- end -}}
