name: HELM Release
on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: J12934/helm-gh-pages-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
